import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-5-27 下午2:28' with Gradle 2.12
 *
 * @author magneto, @date 17-5-27 下午2:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        List<String> lines = new ArrayList<>();
        lines.add("1 aaaa\n");
        lines.add("2 bbbb\n");

        System.out.println(lines);
        lines.stream().toString();
    }
}
