/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'magneto' at '17-5-27 下午2:28' with Gradle 2.12
 *
 * @author magneto, @date 17-5-27 下午2:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
